poll_interval: 2.5
resources: {mineral_threshold: 600, gas_threshold: 600, cooldown: 30}
supply:
  cooldown: 10
  tiers:
  - {max_cap: 25, gap: 3}
  - {max_cap: 50, gap: 5}
  - {max_cap: 200, gap: 10}
workers: {idle_seconds: 10, cooldown: 30}
player_id: 1
tts_voice: Moira
message_mode: strict
screen_capture:
  minerals: [2026, 30, 80, 30]
  gas: [2193, 30, 80, 30]
  supply: [2358, 30, 100, 30]
  idle_workers: [65, 999, 60, 25]
  ocr_threshold: 100
custom_messages:
  supply: []
  minerals: []
  gas: []
  idle_workers: []
